env_name: "FetchPickAndPlace-v4"

# Base Config
flow_cfg: &base_train_cfg
  epoches: 256
  batch_size: 256
  learning_rate: 1.0e-4
  optim_name: 'Adam'
  save_dir: './save/'

# Model
flow: &base_flow
  sde_sigma: 0.5
  time_steps: 10
  hidden_layers: [256, 256, 256]
  use_batch_norm_obs: False
  use_layer_norm_obs: False
  use_ode: True
  use_mid_euler: False
  use_noise_to_supervise: False
  use_new_t_for_training: False

flow2: &flow2
  <<: *base_flow
  hidden_layers: [256, 256, 256, 128]

flow3: &flow3
  <<: *base_flow
  hidden_layers: [256, 256, 256, 128, 64]

flow4: &flow4
  <<: *base_flow
  hidden_layers: [256, 256, 256, 128, 64, 32]

# Imitation Learning Config
il_flow_train: &il_train_cfg
  <<: *base_train_cfg
  teacher_dataset_fp: './save/sac-teacher.pkl'

il_flow_train2:
  <<: *il_train_cfg 
  optim_name: "AdamW"
  save_file_name: "flow-imitation2.pth"

il_flow_train3:
  <<: *il_train_cfg
  optim_name: "AdamW"
  save_file_name: "flow-imitation3.pth"
  # Attention: Large batch size may lead to overfit which cause poor generalization in test.
  batch_size: 256 

il_flow_train4:
  <<: *il_train_cfg
  optim_name: "AdamW"
  save_file_name: "flow-imitation4.pth"
  # Attention: Large batch size may lead to overfit which cause poor generalization in test.
  batch_size: 256 

# Reinforcement Learning Config
flow5: 
  <<: *flow3
  use_ode: True
  use_new_t_for_training: True

rl_flow_train: &rl_train_cfg
  <<: *base_train_cfg
  episode_length: 10000
  num_envs: 10
  batch_size: 2500
  epoches: 1000
  save_file_name: "flow-rl.pth"
  base_model_file_name: "flow-imitation3.pth"
  algorithm: "PPO"

flow_ode:
  <<: *flow3
  use_ode: True

flow_sde:
  <<: *flow3
  use_ode: False

rl_flow_train_gpu: &rl_train_cfg_gpu
  <<: *rl_train_cfg
  episode_length: 51200
  num_envs: 256
  batch_size: 12800
  epoches: 1000
  save_file_name: "flow-rl-gpu.pth"
  save_interval: 10
  save_dir: "./save/flow_rl_gpu"

  save_idx: True
  load_idx: 0

rl_flow_train_sde: 
  <<: *rl_train_cfg_gpu
  save_file_name: "flow-rl-sde.pth"
  save_interval: 10
  save_dir: "./save/flow_rl_sde"
  load_idx: 0